import { addDays, subDays } from "date-fns";
import type { BoardColumn, ScheduleOverview, Task, UserProfile } from "./types";

const now = new Date();
const iso = (date: Date) => date.toISOString();

export const boardColumns: BoardColumn[] = [
  { id: "backlog", title: "Backlog", description: "Ideias, melhorias e demandas novas." },
  { id: "planned", title: "Planejado", description: "Priorizado e vinculado a equipes de escala." },
  { id: "in_progress", title: "Em execucao", description: "Atividades em andamento com acompanhamento da operacao." },
  { id: "review", title: "Revisao", description: "Validacao funcional, operacional e de qualidade." },
  { id: "done", title: "Concluido", description: "Entregas finalizadas e prontas para auditoria." },
];

export const demoUser: UserProfile = {
  id: "demo-user",
  name: "Coordenacao Operacional",
  email: "coordenacao@demo.local",
  role: "Gestor(a) de Escala",
};

export const demoTasks: Task[] = [
  {
    id: "task-1",
    title: "Implantar quadro Kanban integrado",
    description: "Publicar o modulo online e vincular cada card a uma referencia de escala operacional.",
    status: "in_progress",
    priority: "critical",
    assignee: "Time Produto",
    startDate: iso(subDays(now, 2)),
    dueDate: iso(addDays(now, 5)),
    percentComplete: 68,
    createdAt: iso(subDays(now, 7)),
    updatedAt: iso(now),
    labels: ["kanban", "firebase", "escala"],
    linkedShiftId: "shift-1",
    scheduleRef: "ESC-2026-0413-A",
    blockers: ["Aguardando endpoint definitivo do sistema de escala"],
  },
  {
    id: "task-2",
    title: "Gerar relatorio diario em PDF",
    description: "Consolidar cards concluidos, riscos do dia e produtividade por equipe para exportacao em PDF.",
    status: "review",
    priority: "high",
    assignee: "Time BI",
    startDate: iso(subDays(now, 1)),
    dueDate: iso(addDays(now, 2)),
    percentComplete: 88,
    createdAt: iso(subDays(now, 4)),
    updatedAt: iso(now),
    labels: ["pdf", "relatorio"],
    linkedShiftId: "shift-2",
    scheduleRef: "ESC-2026-0413-B",
    blockers: [],
  },
  {
    id: "task-3",
    title: "Disparo de email para liderancas",
    description: "Enviar o resumo diario com anexos em PDF ou PNG para coordenadores e supervisores.",
    status: "planned",
    priority: "medium",
    assignee: "Time Operacoes",
    startDate: iso(now),
    dueDate: iso(addDays(now, 3)),
    percentComplete: 34,
    createdAt: iso(subDays(now, 2)),
    updatedAt: iso(now),
    labels: ["email", "smtp"],
    linkedShiftId: "shift-3",
    scheduleRef: "ESC-2026-0413-C",
    blockers: [],
  },
  {
    id: "task-4",
    title: "Dashboard Gantt executivo",
    description: "Visualizar janela de entrega de cada tarefa, status e dependencia com a escala do dia.",
    status: "done",
    priority: "high",
    assignee: "PMO",
    startDate: iso(subDays(now, 5)),
    dueDate: iso(subDays(now, 1)),
    percentComplete: 100,
    createdAt: iso(subDays(now, 9)),
    updatedAt: iso(subDays(now, 1)),
    labels: ["gantt", "executivo"],
    linkedShiftId: "shift-4",
    scheduleRef: "ESC-2026-0412-D",
    blockers: [],
  },
  {
    id: "task-5",
    title: "Importar escalas do sistema legado",
    description: "Consumir API externa e mapear postos, equipes e janelas de trabalho para o Kanban.",
    status: "backlog",
    priority: "critical",
    assignee: "Integracoes",
    startDate: iso(addDays(now, 1)),
    dueDate: iso(addDays(now, 7)),
    percentComplete: 12,
    createdAt: iso(subDays(now, 1)),
    updatedAt: iso(now),
    labels: ["api", "legado"],
    blockers: ["Endpoint ainda nao entregue pelo sistema principal"],
  },
];

export const demoScheduleOverview: ScheduleOverview = {
  source: "demo",
  connected: false,
  lastSync: iso(now),
  shifts: [
    {
      id: "shift-1",
      title: "Plantonistas - Manha",
      team: "Equipe Alfa",
      date: iso(now),
      startTime: "06:00",
      endTime: "12:00",
      slots: 6,
      status: "confirmed",
    },
    {
      id: "shift-2",
      title: "Atendimento Especial",
      team: "Equipe Beta",
      date: iso(now),
      startTime: "12:00",
      endTime: "18:00",
      slots: 4,
      status: "scheduled",
    },
    {
      id: "shift-3",
      title: "Supervisor Noturno",
      team: "Equipe Gama",
      date: iso(addDays(now, 1)),
      startTime: "18:00",
      endTime: "23:00",
      slots: 2,
      status: "attention",
    },
    {
      id: "shift-4",
      title: "Backoffice Auditado",
      team: "Equipe Delta",
      date: iso(subDays(now, 1)),
      startTime: "08:00",
      endTime: "17:00",
      slots: 3,
      status: "confirmed",
    },
  ],
  alerts: [
    "Equipe Gama com cobertura parcial no proximo turno.",
    "Integracao em modo demonstracao ate apontar a API do sistema de escala.",
  ],
  integrationNotes: [
    "Mapear task.scheduleRef com o identificador oficial da escala.",
    "Substituir o adapter demo pelo endpoint NEXT_PUBLIC_SCHEDULE_API_URL.",
    "Recomenda-se sincronizacao a cada 5 minutos ou via webhook do sistema principal.",
  ],
};
